### ISSUE TITLE
Support for Guzzle 7

### ISSUE THREAD

**Issue by YanCoutu** [cloudblue/connect-php-sdk#60]
Our PHP application use the Laravel framework. We would like to upgrade to the newest version, which require at least Guzzle 7.0.1. However, we are unable to do so because the Connect SDK requires Guzzle 6.

From what I've read, there are few changes between Guzzle 6 and Guzzle 7, so it might be possible for the SDK to support both versions.

**Comment by marcserrat** [comment]
Highly appreciated your PR @YanCoutu!
